---

- block:
    - when: postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

    - when: postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install_migrate_old_data.yml"
  tags:
    - setup-all
    - setup-postgres-backup
    - install-all
    - install-postgres-backup

- block:
    - when: not postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-postgres-backup
